spring.application.name=rs-management

# Database Configuration
#spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce_db
#spring.datasource.username=postgres
#spring.datasource.password=mypassword

#spring.datasource.url=jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:5432/postgres
#spring.datasource.username=postgres.grxxpsnnjiyatcqwymbo
#spring.datasource.password=2852012b.
#spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url=jdbc:postgresql://caboose.proxy.rlwy.net:42763/railway
spring.datasource.username=postgres
spring.datasource.password=OeKwHywTYIXUgtFBeXnbUthJsekSEhsy

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
#application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
application.security.jwt.expiration=3000
application.security.jwt.refresh-token.expiration=3000
logging.level.org.springframework.security=DEBUG

# RSA Key Configuration
rs.key.public-key-file=src/main/resources/keys/public.pem
rs.key.private-key-file=src/main/resources/keys/private.pem
rs.key.secret=jkNF544fDFfdvvdgvDvd5Vd15svd5fvg14vg14d5SDDBVFdbvd5bv1gvvg51dgVDVDv1d5vdvsvBNFNLKHSoledadSmileOpera2TheStar

#config swagger
# Specify the path of the OpenAPI documentation
springdoc.api-docs.path=/v3/api-docs
# Specify the path of the Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html
# Enable or disable Swagger UI
springdoc.swagger-ui.enabled=true
#http://localhost:8080/swagger-ui/index.html
