

#spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/circlek_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC}

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/circlek_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:123456}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT
rs.security.jwt.expiration=${RS_SECURITY_JWT_EXPIRATION:1800}
rs.security.jwt.refresh-token.expiration=${RS_SECURITY_JWT_REFRESH_TOKEN_EXPIRATION:3000}

# RSA Key
rs.key.public-key-file=${RS_KEY_PUBLIC_KEY_FILE:src/main/resources/keys/public.pem}
rs.key.private-key-file=${RS_KEY_PRIVATE_KEY_FILE:src/main/resources/keys/private.pem}
rs.key.secret=${RS_KEY_SECRET:default_secret}
jwt.secret=kGrBPLEe+tTdg3aGNzFfan5KxbgH/eyDobFvhPJ0M3yb3puVeIysWlbG3jAZ2KUL
jwt.expiration=3600000
# Swagger
springdoc.swagger-ui.enabled=${SPRINGDOC_SWAGGER_UI_ENABLED:true}
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# API config
rs.api.main.baseUrl=secured/rest/v1
rs.api.main.publicUrl=public/rest/v1

#logging.level.org.springframework.jdbc.datasource=DEBUG
#logging.level.org.hibernate.SQL=TRACE
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
#logging.level.org.hibernate.engine.jdbc.spi.SqlExceptionHelper=TRACE
#logging.level.org.springframework.transaction=TRACE
#logging.level.org.springframework.orm.jpa=TRACE
#logging.level.org.springframework.security=TRACE

# order
order.generator.enabled=false
order.generator.interval=100000
order.generator.daily-cron:0 0 1 * * *
order.generator.daily-total:100
order.generator.max-lines=4
order.generator.max-realtime-orders=10
order.generator.realtime-hour-weights=1,1,2,3,4,3,2,3,4,3,2,1,2,3,4,3,2,1,1,3,4,3,1,1

#product

product.generator.enabled=false
product.generator.interval=600000
product.generator.max-per-run=3
product.generator.sku-base=10000


