

#spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/circlek_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC}

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/circlek_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:123456}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT
rs.security.jwt.expiration=${RS_SECURITY_JWT_EXPIRATION:1800}
rs.security.jwt.refresh-token.expiration=${RS_SECURITY_JWT_REFRESH_TOKEN_EXPIRATION:3000}

# RSA Key
rs.key.public-key-file=${RS_KEY_PUBLIC_KEY_FILE:src/main/resources/keys/public.pem}
rs.key.private-key-file=${RS_KEY_PRIVATE_KEY_FILE:src/main/resources/keys/private.pem}
rs.key.secret=${RS_KEY_SECRET:default_secret}
jwt.secret=kGrBPLEe+tTdg3aGNzFfan5KxbgH/eyDobFvhPJ0M3yb3puVeIysWlbG3jAZ2KUL
jwt.expiration=36000000
# Swagger
springdoc.swagger-ui.enabled=${SPRINGDOC_SWAGGER_UI_ENABLED:true}
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# API config
rs.api.main.baseUrl=secured/rest/v1
rs.api.main.publicUrl=public/rest/v1

#logging.level.org.springframework.jdbc.datasource=DEBUG
#logging.level.org.hibernate.SQL=TRACE
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
#logging.level.org.hibernate.engine.jdbc.spi.SqlExceptionHelper=TRACE
#logging.level.org.springframework.transaction=TRACE
#logging.level.org.springframework.orm.jpa=TRACE
#logging.level.org.springframework.security=TRACE

# order
order.generator.enabled=false
order.generator.interval=60000
order.generator.daily-cron:0 0 1 * * *
order.generator.daily-total:650
order.generator.max-lines=4
order.generator.max-realtime-orders=10
order.generator.realtime-hour-weights=1,1,2,3,4,3,2,3,4,3,2,1,2,3,4,3,2,1,1,3,4,3,1,1
order.generator.enable-rfm:true
order.generator.enable-abandonment:true
order.generator.safety-stock-pct:0.05

order.generator.enable-allocation:true

#product
product.generator.enabled=false
product.generator.interval=600000
product.generator.max-per-run=3
product.generator.sku-base=10000

# batch
replenishment.enabled=false
# scheduled scan: m?c ??nh m?i 30 phút
replenishment.cron=0 0 0 * * *
# lead time, ??n v?: ngày
replenishment.lead-time-days=1
# min qty/order, pack size m?c ??nh
replenishment.min-order-qty=30
# s? ngày d? tr? mong mu?n sau khi hàng t?i
replenishment.target-cover-days=14
# safety stock heuristic days
replenishment.safety-stock-days=5
# min average daily demand m?c ??nh
replenishment.min-daily-demand=0
# s? order t?i ?a trong 1 run
replenishment.max-orders-per-run=16
# cap t?i ?a cho 1 order
replenishment.max-order-limit=10000
# activation job interval (miliseconds) ? default 60000 (1 phút)
replenishment.activation-interval-ms=60000



